"""
Authentication module for scrcpy network mode.

This module provides HMAC-SHA256 Challenge-Response authentication
for network mode connections, ensuring only authorized clients can
connect to the device.

Security Design:
- Keys are generated by the client (32 bytes, cryptographically random)
- Keys are distributed to the device via ADB (secure channel)
- Authentication uses HMAC-SHA256 Challenge-Response
- Keys are stored locally with restricted permissions (0o600)
- Keys are deleted from device after being read (single-use per session)
"""

import secrets
import hmac
import hashlib
import os
import tempfile
import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# Authentication constants
AUTH_KEY_SIZE = 32  # 256 bits
AUTH_CHALLENGE_SIZE = 32  # 256 bits
AUTH_RESPONSE_SIZE = 32  # 256 bits (HMAC-SHA256 output)

# Key storage directory
AUTH_KEY_DIR = Path.home() / ".config" / "scrcpy-py-ddlx" / "auth_keys"

# Remote key path on device
DEFAULT_REMOTE_KEY_PATH = "/data/local/tmp/scrcpy-auth.key"


class AuthError(Exception):
    """Exception raised when authentication fails."""
    pass


def generate_auth_key() -> bytes:
    """
    Generate a cryptographically secure random key.

    Returns:
        32-byte random key
    """
    return secrets.token_bytes(AUTH_KEY_SIZE)


def save_auth_key(device_serial: str, key: bytes) -> Path:
    """
    Save authentication key to local file.

    Args:
        device_serial: Device serial number (used as filename)
        key: 32-byte authentication key

    Returns:
        Path to saved key file

    Raises:
        OSError: If file cannot be written
    """
    AUTH_KEY_DIR.mkdir(parents=True, exist_ok=True)
    key_path = AUTH_KEY_DIR / f"{device_serial}.key"
    key_path.write_bytes(key)

    # Set restrictive permissions (owner read/write only)
    # On Windows, this may not have full effect but is still good practice
    try:
        key_path.chmod(0o600)
    except OSError:
        logger.warning(f"Could not set permissions on key file: {key_path}")

    logger.info(f"Auth key saved for device {device_serial}")
    return key_path


def load_auth_key(device_serial: str) -> Optional[bytes]:
    """
    Load authentication key from local file.

    Args:
        device_serial: Device serial number

    Returns:
        32-byte key if exists, None otherwise
    """
    key_path = AUTH_KEY_DIR / f"{device_serial}.key"
    if key_path.exists():
        key = key_path.read_bytes()
        if len(key) == AUTH_KEY_SIZE:
            logger.info(f"Auth key loaded for device {device_serial}")
            return key
        else:
            logger.warning(f"Invalid key size for device {device_serial}: {len(key)} bytes")
    return None


def delete_auth_key(device_serial: str) -> bool:
    """
    Delete authentication key from local storage.

    Args:
        device_serial: Device serial number

    Returns:
        True if deleted, False if not found
    """
    key_path = AUTH_KEY_DIR / f"{device_serial}.key"
    if key_path.exists():
        key_path.unlink()
        logger.info(f"Auth key deleted for device {device_serial}")
        return True
    return False


def calculate_hmac(key: bytes, challenge: bytes) -> bytes:
    """
    Calculate HMAC-SHA256 response for challenge.

    Args:
        key: 32-byte authentication key
        challenge: 32-byte challenge from server

    Returns:
        32-byte HMAC-SHA256 digest
    """
    return hmac.new(key, challenge, hashlib.sha256).digest()


def verify_hmac(key: bytes, challenge: bytes, response: bytes) -> bool:
    """
    Verify HMAC-SHA256 response.

    Uses constant-time comparison to prevent timing attacks.

    Args:
        key: 32-byte authentication key
        challenge: 32-byte challenge
        response: 32-byte response to verify

    Returns:
        True if response is valid, False otherwise
    """
    expected = calculate_hmac(key, challenge)
    return hmac.compare_digest(response, expected)


def push_auth_key_to_device(adb_manager, serial: str, key: bytes,
                            remote_path: str = DEFAULT_REMOTE_KEY_PATH) -> bool:
    """
    Push authentication key to device via ADB.

    Args:
        adb_manager: ADBManager instance
        serial: Device serial number
        key: 32-byte authentication key
        remote_path: Remote path on device

    Returns:
        True if successful, False otherwise
    """
    try:
        # Write key to temporary file
        temp_path = Path(tempfile.gettempdir()) / "scrcpy-auth.key"
        temp_path.write_bytes(key)

        # Push to device
        result = adb_manager.push_server(serial, str(temp_path), remote_path)

        # Delete temporary file
        temp_path.unlink()

        logger.info(f"Auth key pushed to device {serial}: {remote_path}")
        return True

    except Exception as e:
        logger.error(f"Failed to push auth key to device: {e}")
        return False
